# Generated by Django 4.1.9 on 2023-06-16 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slugField_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=200), null=True, unique=True),
        ),
    ]
